Fix failure found by TestOperations.testGetRandomAcceptedString (#14227)
* Fix failure found by TestOperations.testGetRandomAcceptedString

string: ?+½]+]+Ř*+[\]ᖴﴁ.

expected: before #14193
java.lang.IllegalArgumentException: expected ']' at position 17

actual: after #14193
REGEXP_CONCATENATION
  REGEXP_CONCATENATION
    REGEXP_CONCATENATION
      REGEXP_CONCATENATION
        REGEXP_CONCATENATION
          REGEXP_CONCATENATION
            REGEXP_CONCATENATION
              REGEXP_CONCATENATION
                REGEXP_REPEAT_MIN min=1
                  REGEXP_CHAR char=?
                REGEXP_CHAR char=½
              REGEXP_REPEAT_MIN min=1
                REGEXP_CHAR char=]
            REGEXP_CHAR char=
          REGEXP_REPEAT_MIN min=1
            REGEXP_CHAR char=]
        REGEXP_REPEAT_MIN min=1
          REGEXP_REPEAT
            REGEXP_CHAR char=Ř
      REGEXP_CHAR_CLASS starts=[] ends=[]
    REGEXP_STRING string=ᖴﴁ
  REGEXP_ANYCHAR

Problem is caused by RegExp accepting too much rather than throwing
exceptions like it should have. The lenience in the parser comes from
"expandPreDefined" which invades on escape character parsing for character
classes (e.g. \s). This one adds a lot of complexity to parsing.

Don't invoke expandPreDefined(), except for the set of characters that it
explicitly handles. This is also consistent with the way
expandPreDefined()'s complexity is managed elsewhere in the parser, such
as in parseSimpleExp().

Add parsing tests for testEmptyClass(), which is unchanged by this PR,
but should be there, and testEscapedInvalidClass(), which fails without
the change.

When we consume an escape, either it matches the predefined special
logic, or we emit range for next(), no other logic: it is an escape.

Add test for escaped '-' in a character class.