Error prone back from the dead (#14201)
* upgrade error-prone to 2.33.0

2.34.0 introduces changes that break the error-prone again, so we can't
go any further than this until they are dealt with.

However: this version is less buggy than the current one and it fixes
compiler issues with JDK21

* Revert "disable error-prone as it is failing CI builds with NoSuchMethodError"

This reverts commit 4cd4f8e2f99b8e300fdd996b54920625a257acf7.

* Fix ComparisonOutOfRange issues found by the new version, which fail build