disable error-prone as it is failing CI builds with NoSuchMethodError
Error-prone fails on valid code with NoSuchMethodErrors, because of its internal API abuse:

An exception has occurred in the compiler (21.0.6). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree$JCExpression com.sun.tools.javac.tree.TreeMaker.Select(com.sun.tools.javac.tree.JCTree$JCExpression, com.sun.tools.javac.code.Symbol)'
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)

Upgrading to the latest version of error-prone won't solve the problem
and only hits different issues with internals.

Disable error-prone until they can fix their code to no longer use
internal java APIs.