Small fix for assertConsistentGraph
TestKnnGraph.testMultipleVectorFields sometimes breaks with
the following message:

java.lang.NullPointerException: Cannot invoke
 "org.apache.lucene.codecs.lucene91.Lucene91HnswVectorsReader.getGraphValues(String)"
because "vectorReader" is null

This happens in assertConsistentGraph.

This patch ensures that for a segment and a field  where there is no
vectors indexed, we don't run a check on consistent graph.